//* This file is part of the MOOSE framework
//* https://www.mooseframework.org
//*
//* All rights reserved, see COPYRIGHT for full restrictions
//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html

#include "AssignFakeNeighborFromList.h"
#include "CastUniquePointer.h"

#include "libmesh/distributed_mesh.h"
#include "libmesh/elem.h"
#include "libmesh/partitioner.h"
#include <typeinfo>
#include <fstream>

registerMooseObject("MooseApp", AssignFakeNeighborFromList);

defineLegacyParams(AssignFakeNeighborFromList);

InputParameters
AssignFakeNeighborFromList::validParams()
{
  InputParameters params = MeshGenerator::validParams();
  params.addRequiredParam<MeshGeneratorName>("input", "The mesh we want to modify");
  params.addClassDescription("Reconstruct fake neighbors generated by BreakMeshByBlock");
  params.addParam<FileName>("fake_neighbor_list_file_name",
                            "FakeNeighborList.txt",
                            "The file name containing the fake neighbor list will be saved");
  return params;
}

AssignFakeNeighborFromList::AssignFakeNeighborFromList(const InputParameters & parameters)
  : MeshGenerator(parameters),
    _input(getMesh("input")),
    _fake_neighbor_list_file_name(getParam<FileName>("fake_neighbor_list_file_name"))
{
  if (typeid(_input).name() == typeid(DistributedMesh).name())
    mooseError("AssignFakeNeighborFromList only works with ReplicatedMesh.");

  readFakeNeighborListFromFile();
}

std::unique_ptr<MeshBase>
AssignFakeNeighborFromList::generate()
{
  std::unique_ptr<MeshBase> mesh = std::move(_input);
  for (const auto & elem : mesh->active_element_ptr_range())
    for (unsigned int s = 0; s < elem->n_sides(); s++)
    {
      std::pair<dof_id_type, unsigned int> elem_side = std::make_pair(elem->id(), s);

      const auto & it_check = _fake_neighbor_map.find(elem_side);
      if (it_check != _fake_neighbor_map.end())
      {
        std::cout << "I need to check if elem " << it_check->first.first << " side "
                  << it_check->first.second << " is ocnnected with elem " << it_check->second.first
                  << " side " << it_check->second.second << " \n";

        // get my s neighbor
        Elem * neighbor = elem->neighbor_ptr(s);
        if (neighbor == nullptr)
        {
          std::cout << "elem " << it_check->first.first << " doesn't have a neighbor on side "
                    << it_check->first.second << ", let's add it \n";

          neighbor = mesh->elem_ptr(it_check->second.first);
          if (neighbor == nullptr)
            std::cout << "I can't get element " << it_check->second.first << " from the mesh \n";
          else
          {
            std::cout << "I found element " << it_check->second.first << " in the mesh \n";
            Elem * neighbor_neighbor = neighbor->neighbor_ptr(it_check->second.second);
            if (neighbor_neighbor == nullptr)
            {
              elem->set_neighbor(s, neighbor);
              neighbor->set_neighbor(it_check->second.second, elem);
            }
            else
              mooseError("neighbor_neighbor is not a null pointer, something is wrong  ");
          }
        }
        else
          std::cout << "elem " << it_check->first.first << " already has a neighbor on side "
                    << it_check->first.second << ", the neighbor id id " << neighbor->id()
                    << " on side " << neighbor->which_neighbor_am_i(elem) << "\n ";
      }
    }

  // // check if elemtn and neighbor are connected
  // if (neighbor == nullptr)
  // {
  //   const auto & it = _fake_neighbor_map.find(elem_side);
  //   if (it != _fake_neighbor_map.end())
  //   {
  //     std::cout << "    neighbor pointer is null i need to stitch \n";
  //
  //     neighbor = mesh->elem_ptr(it->second.first);
  //     if (neighbor != nullptr)
  //     {
  //       std::cout << "I stitched back elem " << it->first.first << " side " << it->first.second
  //                 << " with elem " << it->second.first << " side " << it->second.second << " \n";
  //       elem->set_neighbor(s, neighbor);
  //       neighbor->set_neighbor(it->first.second, elem);
  //     }
  //   }
  // }
  // else
  // {
  //   std::cout << "I laready have a neighbor: my neighbor is element " << neighbor->id()
  //             << " on side " << neighbor->which_neighbor_am_i(elem) << " \n";
  // }
  // }

  // addInterfaceBoundary(*mesh);
  // Partitioner::set_node_processor_ids(*mesh);
  // if (_write_fake_neighbor_list_to_file == true)
  //   readFakeNeighborListFromFile(*mesh);
  return dynamic_pointer_cast<MeshBase>(mesh);
}

void
AssignFakeNeighborFromList::readFakeNeighborListFromFile()
{
  // Read in Euler angles from _file_name
  std::ifstream inFile(_fake_neighbor_list_file_name.c_str());
  if (!inFile)
    mooseError("AssignFakeNeighborFromList can't open ", _fake_neighbor_list_file_name);

  // Skip first line
  for (unsigned int i = 0; i < 1; ++i)
    inFile.ignore(std::numeric_limits<std::streamsize>::max(), '\n');

  // Loop over fake neighbors
  dof_id_type e1, n1;
  unsigned int se1, sn1;

  while (inFile >> e1 >> se1 >> n1 >> sn1)
  {
    std::pair<dof_id_type, unsigned int> epair = std::make_pair(e1, se1);
    std::pair<dof_id_type, unsigned int> npair = std::make_pair(n1, sn1);

    _fake_neighbor_map[epair] = npair;
    _fake_neighbor_map_inverted[npair] = epair;
  }
}
